language: node_js

node_js:
  - "10.8"

cache:
  directories:
    - build # shows bundle size diff per file/chunk
    - "$HOME/.npm" # to avoid fetching modules from npm every time
    - "$HOME/.cache"

before_install: npm install -g greenkeeper-lockfile@1

install: npm ci --loglevel http

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: npm run test-ci
    - stage: test
      name: "End to End Testing"
      script: npm run test-e2e-ci
    - stage: build
      name: "Verify Build"
      script: npm run build-ci
