language: node_js
node_js:
  - '10.8'

addons:
  apt:
    packages:
      - libgconf-2-4 # Required to run Cypress

cache:
  directories:
    - build # shows bundle size diff per file/chunk
    - '$HOME/.cache/Cypress' # for caching the (rather large) Cypress binary

before_install: npm install -g greenkeeper-lockfile@1

install: npm ci --loglevel http

before_script: greenkeeper-lockfile-update

jobs:
  include:
    - stage: test-and-build
      name: 'Unit Testing'
      script: npm run test-ci
      # Running Cypress tests in parallel by running them in batches to reduce pipeline duration.
      # This could probably be improved by writing a Node script to handle a config,
      # though no need to prematurely optimize at this point.
    # - stage: test-and-build
    #   name: 'Integration Testing - Accounts, Events, and Navigation'
    #   env: SPECS='cypress/tests/integration/accounts/**/*,cypress/tests/integration/events/**/*,cypress/tests/integration/navigation/**/*'
    #   script: npm run test-integration-ci
    - stage: test-and-build
      name: 'Integration Testing - Recipients, Templates, and Signals Analytics'
      # env: SPECS='cypress/tests/integration/recipients/**/*,cypress/tests/integration/templates/**/*,cypress/tests/integration/signals-analytics/**/*'
      env: SPECS='cypress/tests/integration/signals-analytics/**/*'
      script: npm run test-integration-ci

after_script: greenkeeper-lockfile-upload

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
