language: node_js
node_js:
  - '10.8'

addons:
  apt:
    packages:
      - libgconf-2-4 # Required to run Cypress

cache:
  directories:
    - build # shows bundle size diff per file/chunk
    - '$HOME/.cache/Cypress' # for caching the (rather large) Cypress binary

before_install: npm install -g greenkeeper-lockfile@1

install: npm ci --loglevel http

before_script: greenkeeper-lockfile-update

jobs:
  include:
    - stage: test-and-build
      name: 'Unit Testing'
      script: npm run test-ci
      # Running Cypress tests in parallel by running them in batches to reduce pipeline duration.
    - stage: test-and-build
      name: 'Integration Testing - Accounts, Events, Navigation, and Alerts'
      script: npm run test-integration-ci -- --specBatch='Paul Walker'
    - stage: test-and-build
      name: 'Integration Testing - Templates, Recipients, and Signals Analytics'
      script: npm run test-integration-ci -- --specBatch='Vin Diesel'

after_script: greenkeeper-lockfile-upload

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
