codecov:
  require_ci_to_pass: yes

# Paths and files that do not contribute to the coverage calculation
ignore:
  - 'src/App.js'
  - 'src/store.js'
  - 'src/config'
  - 'src/reducers'
  - 'third'
  - 'src/__func__'
  - 'src/__testHelpers__'
  - '.storybook'
  - '__mocks__'
  - 'index.js'

coverage:
  precision: 2
  round: down
  range: '70...100' # Coverage is colored green in reports within this range

  # Turned off GitHub status checks - this could be turned on if a level of coverage should be enforced
  status:
    project: off
    patch: off

# These are the default settings that the Codecov docs recommend, though they don't outline their meaning well
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'reach,diff,flags,tree'
  behavior: default
  require_changes: no
