version: 0.2

phases:
  install:
    commands:
      - npm install -g npm

#  pre_build:
#    commands:
#      - npm ci
#      - npm run test-ci
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - echo "list post build contents"
      - cd build
      - ls -la
      - ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
      - cd ..
artifacts:
  files:
    - '**/*'
  base-directory: build
