version: 0.2

phases:
  pre_build:
    commands:
      - npm ci
#      - npm run test-ci
  build:
    commands:
      - npm install
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
