version: 0.2

phases:
  install:
    commands:
      - npm install -g npm

  pre_build:
    commands:
      - npm ci
      - npm run test-ci
  build:
    commands:
      - echo "list contents"
      - ls -la
      - ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'
      - npm install
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
