version: 0.2

phases:
  install:
    commands:
      - npm install -g npm
      - sudo apt-get install git -y

  pre_build:
    commands:
#      - npm ci
#      - npm run test-ci
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - cd build
      - git clone https://GITHUB_USERNAME:$GITHUB_TOKEN@github.com/SparkPost/automation-scripts.git
      - ls -la
      - cd -
artifacts:
  files:
    - '**/*'
  base-directory: build
  secondary-artifacts:
    buildautomation:
      files:
        - '**/*'
      base-directory: automationscripts
