version: 0.2

phases:
  install:
    commands:
      - npm install -g npm
      - sudo apt-get install git -y

  pre_build:
    commands:
#      - npm ci
#      - npm run test-ci
      - git clone https://GITHUB_USERNAME:$GITHUB_TOKEN@github.com/SparkPost/automation-scripts.git
  build:
    commands:
      - npm install
      - npm run build
  post_build:
    commands:
      - echo "list post build contents"
      - cd $CODEBUILD_SRC_DIR
      - ls -la
      - cd -
artifacts:
  files:
    - '**/*'
  base-directory: build
  secondary-artifacts:
    buildautomation:
      files:
        - '**/*'
      base-directory: automationscripts
